name: hdag-benchmark-2
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - iqtree
  - mrbayes
  - newick_utils
  - parallel
  - usher
  - gctree
  - phylip
  - bcftools
  - pip
  - seaborn
  - matplotlib
  - click
  - dendropy
