name: hdag-benchmark3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.7.2
  - appdirs=1.4.4
  - atk-1.0=2.38.0
  - atomicwrites=1.4.1
  - attr=2.5.1
  - bcftools=1.16
  - beagle-lib=4.0.0
  - biopython=1.80
  - boltons=23.0.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - conda=23.3.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cycler=0.11.0
  - dbus=1.13.6
  - dendropy=4.5.2
  - ete3=3.1.2
  - expat=2.5.0
  - fftw=3.3.10
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozendict=2.3.4
  - gctree=4.0.4
  - gdk-pixbuf=2.42.8
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - graphviz=7.0.5
  - gsl=2.7
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=5.3.0
  - htslib=1.16
  - icu=70.1
  - idna=3.4
  - iqtree=2.2.0.3
  - isa-l=2.30.0
  - jack=1.9.21
  - joblib=1.1.1
  - jpeg=9e
  - js2py=0.74
  - jsonpatch=1.33
  - jsonpointer=2.4
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lark=1.1.5
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libcbor=0.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=7.86.0
  - libdb=6.2.32
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libfido2=1.11.0
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgd=2.3.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmamba=1.1.0
  - libmambapy=1.1.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=14.5
  - libprotobuf=3.20.2
  - librsvg=2.54.4
  - libsndfile=1.1.0
  - libsolv=0.7.25
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - lxml=4.9.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mafft=7.515
  - mamba=1.1.0
  - matplotlib=3.6.3
  - matplotlib-base=3.6.3
  - mpg123=1.31.2
  - mpi=1.0
  - mrbayes=3.2.7
  - mscorefonts=0.0.1
  - multiset=3.0.1
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-connector-c=6.1.11
  - mysql-libs=8.0.32
  - ncurses=6.3
  - newick_utils=1.6
  - nspr=4.35
  - nss=3.82
  - numpy=1.24.2
  - openjdk=17.0.3
  - openjpeg=2.5.0
  - openmpi=4.1.2
  - openssh=9.1p1
  - openssl=1.1.1w
  - packaging=23.0
  - pandas=1.5.3
  - pango=1.50.12
  - parallel=20230122
  - patsy=0.5.3
  - pcre2=10.40
  - perl=5.32.1
  - phylip=3.697
  - pillow=9.2.0
  - pip=23.0
  - pixman=0.40.0
  - ply=3.11
  - pooch=1.6.0
  - pthread-stubs=0.4
  - pulseaudio=14.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pydot=1.4.2
  - pyjsparser=2.7.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-graphviz=0.20.1
  - python-tzdata=2022.7
  - python_abi=3.9
  - pytz=2022.7.1
  - pytz-deprecation-shim=0.1.0.post0
  - qt-main=5.15.6
  - readline=8.1.2
  - regex=2022.10.31
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.28.2
  - ruamel.yaml=0.17.40
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=67.1.0
  - sip=6.7.7
  - six=1.16.0
  - statsmodels=0.13.5
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.66.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - tzlocal=4.2
  - ucsc-fatovcf=426
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - usher=0.6.2
  - wheel=0.38.4
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml-cpp=0.7.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - amas==1.0
      - argparse==1.4.0
      - attrs==22.2.0
      - beautifulsoup4==4.11.2
      - exceptiongroup==1.1.1
      - google==3.0.0
      - importlib-resources==5.10.2
      - iniconfig==2.0.0
      - phastsim==0.0.4
      - pluggy==1.0.0
      - protobuf==4.21.12
      - pygtrie==2.5.0
      - pypdf2==3.0.1
      - pytest==7.2.2
      - seqmagick==0.8.4
      - soupsieve==2.3.2.post1
      - tomli==2.0.1
      - zipp==3.12.1
